### ISSUE TITLE
Hard error on edge-case when batches of spectra predictions are combined

### ISSUE THREAD

**Issue by jonasfoe** [wilhelm-lab/koinar#2]
I am encountering errors due to a bug with prediction batching.
This can happen organically when models output matrices, such as AlphaPeptDeep seems to do and I encountered this when doing regular predictions.
Here is a reproducible example forcing the issue:
```
library(koinar)

model <- koinar::Koina(
  model_name = "AlphaPeptDeep_ms2_generic",
  server_url = "koina.wilhelmlab.org"
)
batch_size <- model$batch_size

input <- data.frame(
  peptide_sequences = c(rep("PEPTIDE", batch_size), rep("PEPTIDEPEPTIDE", batch_size)),
  collision_energies = rep(25, 2 * batch_size),
  precursor_charges = rep(2, 2 * batch_size),
  instrument_types = rep("LUMOS", 2 * batch_size)
)

model$predict(input, pred_as_df = FALSE)
```

**Comment by LLautenbacher** [comment]
Hi @jonasfoe, thank you for letting us know about this!
I pushed a new version where this is fixed. You can try it out if you install it via GitHub. 
Let me know if you encounter any other issues with that version!
The Bioconductor version might take a day to update.

**Comment by jonasfoe** [comment]
Thanks for fixing this so fast. It's working great now 👍

**Comment by jonasfoe** [comment]
I recently encountered the issue also with the python client. I don't use the python client typically and don't have the reproducible example at hand but I thought I should let you know. The python package seems to try to rowbind incompatible matrices in just the same way.

**Comment by LLautenbacher** [comment]
Thank you for letting me know! I will look into it!
